apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/evogene1/test-argocd.git'
        revision: HEAD
        # Argo буде шукати кожну папку в overlays/dev/
        files:
          - path: "apps/overlays/dev/*/updater-config.json"
  template:
    metadata:
      # Назва картки буде будуватися динамічно, наприклад: dev-node-red
      name: 'dev-{{path.basename}}'
      labels:
        env: dev
        project: services # Тут ви можете додавати свої теги
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{image}}"
        argocd-image-updater.argoproj.io/{{path.basename}}.update-strategy: "{{strategy}}"
        argocd-image-updater.argoproj.io/{{path.basename}}.version-constraint: "{{constraint}}"
        argocd-image-updater.argoproj.io/write-back-method: "{{writeback}}"
        argocd-image-updater.argoproj.io/write-back-repository: https://github.com/evogene1/test-argocd.git
        argocd-image-updater.argoproj.io/git_creds: secret:argocd/git-token-secret
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/node-red.ignore-differences: "true"
    spec:
      project: default # Можна створити окремий проект "dev-project"
      source:
        repoURL: 'https://github.com/evogene1/test-argocd.git'
        targetRevision: HEAD
        path: '{{appPath}}' # Це автоматично підставить шлях до знайденої папки
      destination:
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        uiControl:
          blockAutomatedSync: false
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: argoproj.io
          kind: Application
          jsonPointers:
            - /spec/syncPolicy/automated