apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Evogene1/test-argocd.git'
    targetRevision: main
    path: apps/overlays/dev  # Указываем папку, где лежат *.yml файлы Application
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false